apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-depl
spec:
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: auth-api
        image: gagandeep39/k8s-node-network-auth-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api-srv
spec:
  selector:
    app: auth-api
  # Reuired to be accessed internally
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP

