apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      # Consists of 2 Pods
      # Auth, Users Pod
      containers:
      - name: users-api
        image: gagandeep39/k8s-node-network-users-api:latest
        env:
          - name: AUTH_URL
            value: auth-api-srv
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
      # - name: auth-api
      #   image: gagandeep39/k8s-node-network-auth-api:latest
      #   resources:
      #     limits:
      #       memory: "128Mi"
      #       cpu: "150m"
---
apiVersion: v1
kind: Service
metadata:
  name: users-api-srv
spec:
  selector:
    app: users-api
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP

