name: Docker push - Frontend

on:
  push:
    branches:
      - '**'
    paths:
      - 'tasks-api/**'

defaults:
  run:
    working-directory: tasks-api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "NOW=v$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV
        # Required for Build and push step
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        # Required for Build and push step
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        # Required for Build and push step
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: tasks-api
          file: tasks-api/Dockerfile
          push: true
          tags: |
            gagandeep39/k8s-node-network-tasks-api:${{env.NOW}}
            gagandeep39/k8s-node-network-tasks-api:latest
